# Arithmetik

Arrays ermöglichen euch, Stapeloperationen auf Daten durchzuführen ohne `for`-Schleifen verwenden zu müssen. Dies wird bei NumPy *Vektorisierung* genannt. Bei allen arithmetischen Operationen zwischen Arrays gleicher Größe wird die Operation elementweise angewendet:

In [1]:
import numpy as np


data = np.random.randn(7, 3)
data

array([[-0.25138295,  0.16045746,  0.56375818],
       [-0.07980581, -0.36607412,  0.02014757],
       [ 1.13948699,  0.32675447, -2.06278216],
       [-0.48238413,  0.80961326, -0.23112316],
       [-0.34032078,  2.00867238,  0.76767972],
       [-0.47347965, -1.47162835, -0.07265641],
       [-1.23260431,  1.26428433, -0.44542326]])

In [2]:
1 / data

array([[ -3.97799449,   6.23218153,   1.77381019],
       [-12.53041607,  -2.73168722,  49.63377927],
       [  0.87758791,   3.06040185,  -0.48478216],
       [ -2.0730367 ,   1.23515763,  -4.32669752],
       [ -2.9384042 ,   0.49784127,   1.30262657],
       [ -2.1120232 ,  -0.67951939, -13.76341108],
       [ -0.81129037,   0.79096132,  -2.24505565]])

In [3]:
data**2

array([[6.31933888e-02, 2.57465955e-02, 3.17823283e-01],
       [6.36896725e-03, 1.34010263e-01, 4.05924543e-04],
       [1.29843060e+00, 1.06768487e-01, 4.25507026e+00],
       [2.32694446e-01, 6.55473632e-01, 5.34179146e-02],
       [1.15818231e-01, 4.03476472e+00, 5.89332154e-01],
       [2.24182975e-01, 2.16568999e+00, 5.27895351e-03],
       [1.51931338e+00, 1.59841486e+00, 1.98401879e-01]])

Vergleich zweier Arrays:

In [4]:
data2 = np.random.randn(7, 3)
data > data2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [False,  True, False]])