# Indizierung und Slicing

Indizierung ist die Auswahl einer Teilmenge eurer Daten oder einzelner Elemente. In eindimensionalen Arrays ist das sehr einfach; verhalten sie sich doch ähnlich wie Python-Listen:

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng()
data = rng.normal(size=(4, 3))
data

array([[ 1.55088682, -0.19252388, -0.41198448],
       [-0.85917748, -0.62768546,  1.21933903],
       [ 0.8389391 , -0.88456804, -0.67016679],
       [-1.70774438, -0.78328505,  0.37689532]])

In [3]:
data[3]

array([-1.70774438, -0.78328505,  0.37689532])

In [4]:
data[1:3]

array([[-0.85917748, -0.62768546,  1.21933903],
       [ 0.8389391 , -0.88456804, -0.67016679]])

In [5]:
data[1:3] = rng.normal(size=(2, 3))

In [6]:
data

array([[ 1.55088682, -0.19252388, -0.41198448],
       [ 1.06439017, -0.68654884,  1.1958988 ],
       [ 0.22420899, -0.09198245, -0.1812715 ],
       [-1.70774438, -0.78328505,  0.37689532]])

<div class="alert alert-block alert-info">

**Bemerkung:**

Array-Slices unterscheiden sich von Python-Listen dadurch, dass sie Sichten (_views_) auf das ursprüngliche Array sind. Das bedeutet, dass die Daten nicht kopiert werden und dass alle Änderungen an der View im Ausgangsarray wiedergegeben werden.

Wenn ihr eine Kopie eines Teils eines `ndarray` erstellen wollt, könnt ihr das Array explizit kopieren – z.B. mit `data[2:5].copy()`.
</div>

_Slicing_ in dieser Weise führt immer zu Array-Ansichten mit der gleichen Anzahl von Dimensionen. Wenn ihr jedoch ganzzahlige Indizes und Slices mischt, erhaltet ihr Slices mit niedrigeren Dimensionen. So können wir z.B. die zweite Zeile, aber nur die ersten beiden Spalten wie folgt auswählen:

In [7]:
data[1, :2]

array([ 1.06439017, -0.68654884])

Ein Doppelpunkt bedeutet, dass die gesamte Achse genommen wird, so dass ihr auch höherdimensionale Achsen auswählen könnt:

In [8]:
data[:, :1]

array([[ 1.55088682],
       [ 1.06439017],
       [ 0.22420899],
       [-1.70774438]])

## Boolesche Indizierung

Betrachten wir ein Beispiel, bei dem wir einige Daten in einem Array und ein Array von Namen mit Duplikaten haben. Ich werde hier die Funktion `randn` in `numpy.random` verwenden, um einige zufällige normalverteilte Daten zu erzeugen:

In [9]:
names = np.array(
    [
        "Andrea",
        "Tim",
        "Veit",
        "Tim",
    ]
)

In [10]:
names

array(['Andrea', 'Tim', 'Veit', 'Tim'], dtype='<U6')

In [11]:
data

array([[ 1.55088682, -0.19252388, -0.41198448],
       [ 1.06439017, -0.68654884,  1.1958988 ],
       [ 0.22420899, -0.09198245, -0.1812715 ],
       [-1.70774438, -0.78328505,  0.37689532]])

Angenommen, jeder Name entspricht einer Zeile im Datenarray und wir wollen alle Zeilen mit dem entsprechenden Namen _Tim_ auswählen. Wie arithmetische Operationen werden auch Vergleiche wie `==` mit Arrays vektorisiert. Der Vergleich von Namen mit der Zeichenkette `Tim` ergibt also ein boolesches Array:

In [12]:
names == "Tim"

array([False,  True, False,  True])

Dieses boolesche Array kann beim Indizieren des Arrays übergeben werden:

In [13]:
data[names == "Tim"]

array([[ 1.06439017, -0.68654884,  1.1958988 ],
       [-1.70774438, -0.78328505,  0.37689532]])

Dabei muss das boolesche Array die gleiche Länge haben wie die Arrayachse, die es indiziert.

<div class="alert alert-block alert-info">

**Bemerkung:**

Die Auswahl von Daten aus einem Array durch boolesche Indizierung und die Zuweisung des Ergebnisses an eine neue Variable erzeugt immer eine Kopie der Daten, selbst wenn das zurückgegebene Array unverändert ist.
</div>

Im folgenden Beispiel wähle ich die Zeilen aus, in denen `Namen == "Tim"` ist und indiziere auch die Spalten:

In [14]:
data[names == "Tim", 2:]

array([[1.1958988 ],
       [0.37689532]])

Um alles außer _Tim_ auszuwählen, könnt ihr entweder `!=` verwenden oder die Bedingung mit `~` negieren:

In [15]:
names != "Tim"

array([ True, False,  True, False])

In [16]:
cond = names == "Tim"
data[~cond]

array([[ 1.55088682, -0.19252388, -0.41198448],
       [ 0.22420899, -0.09198245, -0.1812715 ]])

Wenn ihr zwei der drei Namen auswählt, um mehrere boolesche Bedingungen zu kombinieren, könnt ihr die booleschen arithmetischen Operatoren `&` (und) und `|` (oder) verwenden.

<div class="alert alert-block alert-warning">

**Warnung:**

Die Python-Schlüsselwörter `and` und `or` funktionieren nicht mit booleschen Arrays.
</div>

In [17]:
mask = (names == "Tim") | (names == "Veit")

In [18]:
mask

array([False,  True,  True,  True])

In [19]:
data[mask]

array([[ 1.06439017, -0.68654884,  1.1958988 ],
       [ 0.22420899, -0.09198245, -0.1812715 ],
       [-1.70774438, -0.78328505,  0.37689532]])

## Ganzzahlige Array-Indizierung

Ganzzahlige Array-Indizierung ermöglicht die Auswahl beliebiger Elemente im Array auf der Grundlage eures N-dimensionalen Index. Jedes Integer-Array repräsentiert eine Anzahl von Indizes in dieser Dimension. 

<div class="alert alert-block alert-info">

**Siehe auch:**

* [Integer array indexing](https://numpy.org/doc/stable/user/basics.indexing.html#integer-array-indexing)
</div>