# Mathematische und statistische Methoden

Eine Reihe von mathematischen Funktionen, die Statistiken über ein ganzes Array oder über die Daten entlang einer Achse berechnen, sind als Methoden der Array-Klasse zugänglich. So könnt ihr Aggregationen verwenden wie Summe, Mittelwert und Standardabweichung, indem ihr entweder die Array-Instanzmethode aufruft oder die NumPy-Funktion der obersten Ebene verwendet.

Im folgenden generiere ich einige normalverteilte Zufallsdaten und berechne einige aggregierte Statistiken:

In [1]:
import numpy as np


data = np.random.randn(7, 3)

data

array([[ 0.18843607,  0.88915798, -1.02312149],
       [-0.54203693,  0.59941042, -0.53122088],
       [ 0.06076139, -0.21311012, -0.88051756],
       [ 0.24406085, -0.58979742,  0.94331326],
       [-0.29601087,  1.77604065,  0.81100665],
       [-1.09810936, -1.52484115,  0.35186377],
       [-0.45311951, -0.95634787, -0.65011365]])

In [2]:
data.mean()

np.float64(-0.13782360834805996)

In [3]:
np.mean(data)

np.float64(-0.13782360834805996)

In [4]:
data.sum()

np.float64(-2.894295775309259)

Funktionen wie `mean` und `sum` benötigen ein optionales Achsenargument, das die Statistik über die angegebene Achse berechnet, was zu einem Array mit einer Dimension weniger führt:

In [5]:
data.mean(axis=0)

array([-0.27085977, -0.00278393, -0.13982713])

In [6]:
data.sum(axis=0)

array([-1.89601836, -0.0194875 , -0.97878991])

Mit `data.mean(0)`, was dasselbe ist wie `data.mean(axis=0)`, wird der Mittelwert über die Zeilen berechnet, während `data.sum(0)` die Summe über die Zeilen berechnet.

Andere Methoden wie `cumsum` und `cumprod` aggregieren hingegen nicht, sondern erzeugen ein neues Array mit den Zwischenergebnissen.

In mehrdimensionalen Arrays geben Akkumulationsfunktionen wie `cumsum` und `cumprodm` ein Array derselben Größe zurück, aber mit den entlang der angegebenen Achse berechneten Teilaggregaten:

In [7]:
data.cumsum()

array([ 0.18843607,  1.07759404,  0.05447255, -0.48756438,  0.11184604,
       -0.41937485, -0.35861345, -0.57172357, -1.45224112, -1.20818027,
       -1.79797769, -0.85466443, -1.1506753 ,  0.62536534,  1.436372  ,
        0.33826264, -1.18657851, -0.83471474, -1.28783426, -2.24418212,
       -2.89429578])

In [8]:
data.cumprod()

array([ 1.88436066e-01,  1.67549431e-01, -1.71423423e-01,  9.29178263e-02,
        5.56959130e-02, -2.95868322e-02, -1.79773715e-03,  3.83115971e-04,
       -3.37340339e-04, -8.23315706e-05,  4.85589476e-05,  4.58062991e-05,
       -1.35591625e-05, -2.40816237e-05, -1.95303569e-05,  2.14464678e-05,
       -3.27024565e-05, -1.15068095e-05,  5.21395994e-06, -4.98635947e-06,
        3.24170036e-06])

Grundlegende statistische Methoden für Arrays:

Methode | Beschreibung
:------ | :-----------
`sum` | Summe aller Elemente im Array oder entlang einer Achse
`mean` | Arithmetisches Mittel; bei Arrays mit der Länge Null wird`NaN` zurückgegeben 
`std`, `var` | Standardabweichung bzw. Varianz
`min`, `max` | Minimum und Maximum
`argmin`, `argmax` | Indizes der minimalen bzw. maximalen Elemente
`cumsum` | Kumulative Summe der Elemente, beginnend mit `0`
`cumprod` | Kumulatives Produkt der Elemente, beginnend mit `1`