# Mathematische und statistische Methoden

Eine Reihe von mathematischen Funktionen, die Statistiken über ein ganzes Array oder über die Daten entlang einer Achse berechnen, sind als Methoden der Array-Klasse zugänglich. So könnt ihr Aggregationen verwenden wie Summe, Mittelwert und Standardabweichung, indem ihr entweder die Array-Instanzmethode aufruft oder die NumPy-Funktion der obersten Ebene verwendet.

Im folgenden generiere ich einige normalverteilte Zufallsdaten und berechne einige aggregierte Statistiken:

In [1]:
import numpy as np


rng = np.random.default_rng()
data = rng.random((7, 3))

data

array([[0.79440596, 0.10972775, 0.35435383],
       [0.74358108, 0.43438519, 0.83743312],
       [0.94298041, 0.39124331, 0.08939286],
       [0.18968082, 0.60070664, 0.5113487 ],
       [0.76300762, 0.88587544, 0.6838369 ],
       [0.714206  , 0.17504049, 0.58097537],
       [0.22871752, 0.95094866, 0.99379828]])

In [2]:
data.mean()

np.float64(0.5702688544567261)

In [3]:
np.mean(data)

np.float64(0.5702688544567261)

In [4]:
data.sum()

np.float64(11.97564594359125)

Funktionen wie `mean` und `sum` benötigen ein optionales Achsenargument, das die Statistik über die angegebene Achse berechnet, was zu einem Array mit einer Dimension weniger führt:

In [5]:
data.mean(axis=0)

array([0.62522563, 0.50684678, 0.57873415])

In [6]:
data.sum(axis=0)

array([4.3765794 , 3.54792749, 4.05113905])

Mit `data.mean(0)`, was dasselbe ist wie `data.mean(axis=0)`, wird der Mittelwert über die Zeilen berechnet, während `data.sum(0)` die Summe über die Zeilen berechnet.

Andere Methoden wie `cumsum` und `cumprod` aggregieren hingegen nicht, sondern erzeugen ein neues Array mit den Zwischenergebnissen.

In mehrdimensionalen Arrays geben Akkumulationsfunktionen wie `cumsum` und `cumprodm` ein Array derselben Größe zurück, aber mit den entlang der angegebenen Achse berechneten Teilaggregaten:

In [7]:
data.cumsum()

array([ 0.79440596,  0.90413371,  1.25848754,  2.00206862,  2.43645381,
        3.27388693,  4.21686734,  4.60811065,  4.69750351,  4.88718433,
        5.48789098,  5.99923968,  6.76224729,  7.64812274,  8.33195963,
        9.04616563,  9.22120611,  9.80218148, 10.030899  , 10.98184767,
       11.97564594])

In [8]:
data.cumprod()

array([7.94405957e-01, 8.71683779e-02, 3.08884486e-02, 2.29680659e-02,
       9.97698767e-03, 8.35505991e-03, 7.87865783e-03, 3.08247220e-03,
       2.75551012e-04, 5.22667412e-05, 3.13969787e-05, 1.60548043e-05,
       1.22499380e-05, 1.08519192e-05, 7.42094275e-06, 5.30008181e-06,
       9.27728893e-07, 5.38987633e-07, 1.23275916e-07, 1.17229068e-07,
       1.16502046e-07])

Grundlegende statistische Methoden für Arrays:

Methode | Beschreibung
:------ | :-----------
`sum` | Summe aller Elemente im Array oder entlang einer Achse
`mean` | Arithmetisches Mittel; bei Arrays mit der Länge Null wird`NaN` zurückgegeben 
`std`, `var` | Standardabweichung bzw. Varianz
`min`, `max` | Minimum und Maximum
`argmin`, `argmax` | Indizes der minimalen bzw. maximalen Elemente
`cumsum` | Kumulative Summe der Elemente, beginnend mit `0`
`cumprod` | Kumulatives Produkt der Elemente, beginnend mit `1`