# Universelle Funktionen (`ufunc`)

Eine universelle Funktion, oder `ufunc`, ist eine Funktion, die elementweise Operationen auf Daten in `ndarrays` durchführt. Man kann sie sich als schnelle vektorisierte Wrapper für einfache Funktionen vorstellen, die einen oder mehrere skalare Werte annehmen und ein oder mehrere skalare Ergebnisse erzeugen.

Viele `ufuncs` sind einfache elementweise Transformationen, wie [sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html) oder [exp](https://numpy.org/doc/stable/reference/generated/numpy.exp.html):

In [1]:
import numpy as np


data = np.arange(10)

In [2]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(data)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(data)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Diese werden als einstellige ufuncs bezeichnet. Andere, wie [add](https://numpy.org/doc/stable/reference/generated/numpy.add.html) oder [maximum](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html), nehmen zwei Arrays (also binäre ufuncs) und geben ein einziges Array als Ergebnis zurück:

In [5]:
import numpy as np


rng = np.random.default_rng()
x = rng.normal(size=8)
y = rng.normal(size=8)
x, y

(array([-0.44268441,  0.91852841, -3.0452678 , -0.19302094,  1.04784189,
         0.78246093, -1.24320392, -0.85376618]),
 array([ 0.00448541, -1.31346391,  0.29722027,  2.53364962,  0.06792141,
        -1.52562906, -0.25359309,  0.45988813]))

In [6]:
np.maximum(x, y)

array([ 0.00448541,  0.91852841,  0.29722027,  2.53364962,  1.04784189,
        0.78246093, -0.25359309,  0.45988813])

Hier berechnete `numpy.maximum` das elementweise Maximum der Elemente in `x` und `y`.

Manche `ufunc`, wie z.B. [modf](https://numpy.org/doc/stable/reference/generated/numpy.modf.html) , eine vektorisierte Version des eingebauten Python [divmod](https://docs.python.org/3/library/functions.html#divmod), geben mehrere Arrays zurückgeben: die Bruch- und Integralteile eines Gleitkomma-Arrays:

In [7]:
data = x * 5

In [8]:
data

array([ -2.21342203,   4.59264206, -15.22633899,  -0.96510468,
         5.23920946,   3.91230463,  -6.2160196 ,  -4.26883088])

In [9]:
remainder, whole_part = np.modf(x)

In [10]:
remainder

array([-0.44268441,  0.91852841, -0.0452678 , -0.19302094,  0.04784189,
        0.78246093, -0.24320392, -0.85376618])

In [11]:
whole_part

array([-0.,  0., -3., -0.,  1.,  0., -1., -0.])

Ufuncs akzeptieren ein optionales `out`-Argument, das es euch erlaubt, eure Ergebnisse an ein bestehendes Array zu übertragen, anstatt ein neues zu erstellen:

In [12]:
out = np.zeros_like(data)

In [13]:
np.add(data, 1)

array([ -1.21342203,   5.59264206, -14.22633899,   0.03489532,
         6.23920946,   4.91230463,  -5.2160196 ,  -3.26883088])

In [14]:
np.add(data, 1, out=out)

array([ -1.21342203,   5.59264206, -14.22633899,   0.03489532,
         6.23920946,   4.91230463,  -5.2160196 ,  -3.26883088])

In [15]:
out

array([ -1.21342203,   5.59264206, -14.22633899,   0.03489532,
         6.23920946,   4.91230463,  -5.2160196 ,  -3.26883088])

Einige einstellige ufuncs:

Funktion | Beschreibung
:------- | :-----------
`abs`, `fabs` | berechnet den absoluten Wert elementweise für Ganzzahl-, Gleitkomma- oder komplexe Werte
`sqrt` | berechnet die Quadratwurzel aus jedem Element (entspricht `data ** 0,5`)
`square` | berechnet das Quadrat eines jeden Elements (entspricht `data ** 2`)
`exp` | berechnet die Exponentialfunktion aller Elemente in einem Eingabearray
`log`, `log10`, `log2`, `log1p` | Natürlicher Logarithmus (Basis e), log Basis 10, log Basis 2 bzw. log(1 + x)
`sign` | berechnet das Vorzeichen jedes Elements: `1` (positiv), `0` (Null), oder `-1` (negativ)
`ceil` | berechnet die Obergrenze jedes Elements (d.h. die kleinste ganze Zahl, die größer oder gleich dieser Zahl ist)
`floor` | berechnet die Untergrenze jedes Elements (d.h. die größte ganze Zahl, die kleiner oder gleich jedem Element ist)
`rint` | rundet Elemente auf die nächste Ganzzahl, wobei der `dtype` erhalten bleibt
`modf` | gibt den gebrochenen und ganzzahligen Teile des Arrays als separate Arrays zurück
`isnan` | gibt ein boolesches Array zurück, das angibt, ob jeder Wert `NaN` (Not a Number) ist
`isfinite`, `isinf` | gibt ein boolesches Array zurück, das angibt, ob jedes Element endlich (non-`inf`, not-`NaN`) bzw. unendlich ist
`cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | reguläre und hyperbolische trigonometrische Funktionen
`arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometrische Funktionen
`logical_not` | berechnet den Wahrheitswert von `not x` elementweise (entspricht `~data`)

Einige binäre universelle Funktionen:

Funktion | Beschreibung
:------- | :-----------
`add` | hinzufügen entsprechender Elemente in Arrays
`subtract` | subtrahiert Elemente im zweiten Array vom ersten Array
`multiply` | Array-Elemente multiplizieren
`divide`, `floor_divide` | Dividieren oder Abschneiden des Rests
`power` | erhöht Elemente im ersten Array auf die im zweiten Array angegebenen Potenzen
`maximum`, `fmax` | elementweises Maximum; `fmax` ignoriert `NaN`
`minimum`, `fmin` | elementweises Minimum; `fmin` ignoriert `NaN`
`mod` | Elementweiser Modulus (Rest der Division)
`copysign` | kopiert das Vorzeichen der Werte im zweiten Argument auf die Werte im ersten Argument
`greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | Elementweise Vergleiche durchführen, die ein boolesches Array ergeben (entspricht den Infix-Operatoren `>`, `>=`, `<`, `<=`, `==`, `!=`)
`logical_and` |berechnet den elementweisen Wahrheitswert der logischen Operation AND (`&`).
`logical_or` | berechnet den elementweisen Wahrheitswert der logischen Operation OR (`|`).
`logical_xor` | berechnet den elementweisen Wahrheitswert der logischen Operation XOR (`^`).

<div class="alert alert-block alert-info">

**Hinweis:**

Eine vollständige Übersicht über binäre universelle Funktionen findet ihr in [Universal functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html).
</div>