# Bedingte Logik als Array-Operationen – `where`

Die Funktion [numpy.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html) ist eine vektorisierte Version von `if` und `else`.

Im folgenden Beispiel erzeugen wir zunächst ein boolesches Array und zwei Arrays mit Werten:

In [1]:
import numpy as np

In [2]:
cond = [False, True, False, True, False, False, False]
default_rng = np.random.default_rng()
data1 = default_rng.random(7)
data2 = default_rng.random(7)

Nun wollen wir Nehmen wir die Werte aus `data1` übernehmen, wenn der entsprechende Wert in `cond` `True` ist und ansonsten den Wert aus `data2` übernommen wird. Mit Pythons `if`-`else` könnte das wie folgt aussehen:

In [3]:
result = np.array(
    [(x if c else y) for x, y, c in zip(data1, data2, cond, strict=True)]
)

result

array([0.16844595, 0.13383096, 0.14577336, 0.88793674, 0.92631339,
       0.3457434 , 0.26741888])

Dies hat jedoch die folgenden beiden Probleme:

* bei großen Arrays wird die Funktion nicht sehr schnell sein
* dies funktioniert nicht mit mehrdimensionalen Arrays

Mit `np.where` könnt ihr diese Probleme in einem einzigen Funktionsaufruf umgehen:

In [4]:
result = np.where(cond, data1, data2)

result

array([0.16844595, 0.13383096, 0.14577336, 0.88793674, 0.92631339,
       0.3457434 , 0.26741888])

Das zweite und dritte Argument von `np.where` müssen keine Arrays sein; eines oder beide können auch Skalare sein. Eine typische Anwendung von `where` in der Datenanalyse besteht darin, ein neues Array von Werten auf der Grundlage eines anderen Arrays zu erzeugen. Angenommen, ihr habt eine Matrix mit zufällig generierten Daten und möchtet alle negativen Werte zu positiven Werten machen:

In [5]:
data = default_rng.random(size=(4, 4))

data

array([[0.5174118 , 0.75948355, 0.07032055, 0.63606893],
       [0.14624666, 0.80580928, 0.58179459, 0.62943746],
       [0.12583249, 0.30487534, 0.23080507, 0.26672527],
       [0.21664821, 0.6181373 , 0.61761915, 0.18154932]])

In [6]:
data > 0.9

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [7]:
np.where(data > 0.9, np.nan, data)

array([[0.5174118 , 0.75948355, 0.07032055, 0.63606893],
       [0.14624666, 0.80580928, 0.58179459, 0.62943746],
       [0.12583249, 0.30487534, 0.23080507, 0.26672527],
       [0.21664821, 0.6181373 , 0.61761915, 0.18154932]])